### PR TITLE
Added paragraph re: lone researchers to the introduction

### PR DESCRIPTION
**Pull request by lwjohnst86**
I made some minor edits to fix typos, clarification, wording, and grammatical issues. I also added a section on lone researchers. See https://github.com/swcarpentry/git-novice/issues/63 for a small discussion on this issue. The Git introduction is heavily focused on collaboration, but at least in my field/area, collaboration is still in the infant stages, if it exists at all (especially regarding code).

### CODE REVIEW

**Comment by iglpdc** [comment]
Hey, @lwjohnst86, thanks a lot for all the typo fixing: it was great! I made some comments, could you take a look? I liked also the comment for the solo researcher, let's see if we can closed the discussions on that point with your PR.

It would be great to split this PR in two, one for the typo fixing and one for the solo researcher paragraph. It's a bit tricky, but it would be good Git-voodoo practice: I'll have time the day after tomorrow to go thru the commands to do it (if you know how to do it, just go ahead).  

Thanks again!

**Comment by lwjohnst86** [comment]
Thanks @iglpdc! I'll try my hand at doing some Git-voodoo and submit two pull requests as you suggested. If I fail at it, I'll ask for you advice! :)

**Comment by lwjohnst86** [comment]
@iglpdc, I've split the PR into two as you suggested. I hope I did it right :)

**Comment by iglpdc** [comment]
I think this is good too. Thanks again @lwjohnst86. I'm merging.

**Pull request merged**
