### PR TITLE
adding information about cloning to topic 7

### PR DESCRIPTION
**Pull request by ChristinaLK**
I created this PR as part of a demo - probably needs further discussion!  

Created in response to #176

### CODE REVIEW

**Comment by daisieh** [comment]
We cover cloning in the next lesson; we should just move this objective there.

**Comment by ChristinaLK** [comment]
ok!  Is there anything here that's worth moving to the next section?

**Comment by daisieh** [comment]
I will take a look! Thanks, @ChristinaLK :)

**Comment by daisieh** [comment]
Augh sorry, it turns out I was thinking of a different version of the lesson that I'd created and is hiding in a branch.

**Comment by daisieh** [comment]
Actually, now that I look *again*, cloning is definitely in 08-collab. I'm going to close this one without merging, but thanks for the contribution, @ChristinaLK!

**Pull request closed without merging**
