### PR TITLE
Add descriptive alt text to all images

### PR DESCRIPTION
**Pull request by multimeric**
My sense is that some of the current image alt texts are not descriptive enough. For example "The Git Commit Workflow" is more of a title than a description. I have generally attempted to follow the following principles: https://carpentries.org/blog/2022/11/accathon/.

### CODE REVIEW

**Comment by pgmccann** [comment]
I like these, and think they are generally a big improvement, but I have a concern about the accessibility of text which references "the previous/earlier diagram". I believe it is generally not good practice to refer to an element of a webpage by its position alone.

**Comment by martinosorb** [comment]
Thank you for the PR @multimeric. If you can think of a meaninful way to change your alt texts according to @pgmccann's comment, that would be great. Otherwise I will merge as-is, which is already a clear improvement.

**Comment by multimeric** [comment]
Okay, I'll try to think about how I might explain these diagrams without referring to earlier diagrams, but I think it might end up being quite verbose.

**Comment by martinosorb** [comment]
Thank you @multimeric.
@kekoziar I will merge unless you have objections.

**Comment by multimeric** [comment]
Sure, this is all good from my end.

**Pull request merged**
