### PR TITLE
Added ignore challenge to ignore.md

### PR DESCRIPTION
**Pull request by Seanny123**
Submitting this pull request in an effort to complete the Software Carpentry Instructor training.

### CODE REVIEW

**Comment by daisieh** [comment]
I agree with @iglpdc

**Comment by iglpdc** [comment]
@Seanny123 yes, maybe you could add a one-line hint.

**Comment by Seanny123** [comment]
Added more challenges. Let me know what you think of these ones. (:

**Comment by iglpdc** [comment]
Oh, I really like it! Well done @Seanny123, thanks for taking the extra effort of adding more challenges. I'm merging.

**Pull request merged**
