### PR TITLE
Add missing periods in ep 05

### PR DESCRIPTION
**Pull request by tomeknd**
This is my first ever PR, so any feedback appreciated if applicable. Thank you for maintaining this awesome project!

### CODE REVIEW

**Comment by martinosorb** [comment]
Thank you for catching the missing periods and for taking the time to submit this PR. I have to point out that the first change would render as `git restore .`. which looks an awful lot like `git restore ..` which is a different command (referring to the parent directory `..` rather than the current directory `.`). So I would avoid the period there to avoid confusion...

**Comment by tomeknd** [comment]
Makes sense, thank you for the feedback. If the other edit is to be applied, is there any further action needed on my part?

**Comment by martinosorb** [comment]
I've updated it myself.
I will not merge for a while because we are waiting for a larger merge which I don't want to conflict with this. Thank you.

**Comment by tomeknd** [comment]
Thank you.

**Pull request merged**
