### PR TITLE
Git novice typo lesson 7_line 152

### PR DESCRIPTION
**Pull request by eturnator**

### CODE REVIEW

**Comment by munkm** [comment]
Hi @eturnator! Thank you for your catch in lesson 7. Can you tell me more about why you want to add the additional line to lesson 10?

**Comment by kekoziar** [comment]
@munkm I think this duplicates [PR #660](https://github.com/swcarpentry/git-novice/pull/660).

**Comment by munkm** [comment]
Ah, ok I see that now. Thanks @kekoziar!

@eturnator, I think what @kekoziar meant by opening separate PRs for different changes was not to submit an additional Pull Request with the same set of changes but a different title. Instead, you'd open one Pull Request with only the changes that are in lesson 10 (with the discussion in the aforementioned PR), and then a second Pull Request with only the changes for the typo fix. If you'd like some help doing that that, I'm happy to do so.

**Comment by eturnator** [comment]
660 and 677 are separate pull requests. I don’t have anything to add about 660; it was a suggestion, I can see the argument both ways (Re3 may or may not be confusing for novices), so I leave the decision to authors. 

If you’d like me to do something else with #677, then, yes please explain the steps involved. 

Thank you,
Ece

**Comment by munkm** [comment]
Hi @eturnator!

You absolutely submitted separaate pull requests with different titles, but the same changes exist on both pull requests. Next to the commit messages in this pull request there are hashes that identify the unique changes that would be incorporated to this repository if this pull request were to be merged. In this PR, you're requesting that changes `6931edd`, `5d063aa`,  `b5e2e78` and `e0c4f09` be added. In swcarpentry/git-novice#660 those same identifiers are requesting to be added. So you've opened two pull requests, but both contain the same exact set of changes. If one PR were to be merged, the other one wouldn't incorporate anything new.  

To do what @kekoziar asked, you'll want to update each of the branches that you're suggesting the Pull Request from (for this pull request it is `git-novice-typos` and for #660 it is `gh-pages` to have only the changes that are relevant to the title of your pull request. We can help you do this if you'd like.

**Comment by eturnator** [comment]
Hi Madicken,
Yes I created a bit of a mess when I was trying to separate the PRs out.
Can you tell me what the best strategy would be? A revert command? Please
advise and I'll get to it ( asap but definitely after vacation).
Thank you and @kekoziar <https://github.com/kekoziar> !
Ece

**Comment by kekoziar** [comment]
Hi @eturnator.  I'll be honest, I haven't used the revert button so much, so I won't speak to that but how to submit the new PRs from different branches (we can always close the current PRs if you submit new ones). There are a few options, depending on how comfortable you are in the command line or browser interface.  Basically, there are three steps
1. Update your forked repository of git-novice
2. Create one branch for each change
3. Push the changes to the main git-novice repository.

For the browser interface, the easiest way to update your forked repository is delete your current repository and create a new fork of git-novice.  Your PRs in the main repository will still be there, so you can reference the changes that way.

To create a new branch through the browser, click on `Branch: gh-pages` (gh-pages should automatically be selected as the main branch when you fork the repository; if it isn't select it, then click on `Branch: gh-pages`). There will be a text box that allows you to find or create a branch; start typing the name of your branch.  I like to reference the issue number in my branch names, to keep track of what issue I'm working with.  Github will prompt you `Create branch: Branch-name from 'gh-pages'` click that, and then you have a branch for your changes.  

Once you've made your changes, on the main `<>Code` page, there should now be a message that you can `Compare & pull request` that allows you to push your changes to the main repository as a PR.

Using the command line is a little more in-depth.  I can write instructions a little later, when I have time.

**Comment by munkm** [comment]
@kekoziar eturnator already has submitted these PRs from separate branches.

**Comment by kekoziar** [comment]
But the first was made from his gh-pages, which is why the the changes from the first PR are reflected in the second PR.  gh-pages of a fork should always reflect gh-pages of the main, with changes pushed from branches made from gh-pages.

**Review by kekoziar — APPROVED** [review]
Approve typo fix in episode 7.

**Pull request merged**
