### PR TITLE
Fix solution to exercise in episode 7

### PR DESCRIPTION
**Pull request by amaji**
This pull request fixes https://github.com/swcarpentry/git-novice/issues/541

We never created a local README file as part of this lesson. Therefore, it is incorrect to say that a local version is the cause of merge conflict. 

Please verify layout, since the solution nests various classes.

### CODE REVIEW

**Comment by nhejazi** [comment]
Thanks for contributing this revised solution --- the content looks good. I just had a chance to review this and it appears that the formatting is a bit off. That is, using `jekyll serve` to build the site shows that the new section in lesson 7 does not follow the same formatting as the previous examples. Happy to merge this once that minor change is resolved.

**Comment by amaji** [comment]
@nhejazi Thanks for reviewing. Can you please point me to some documentation about how to view the formatting in my personal fork? Let me know how we can resolve this.

**Comment by nhejazi** [comment]
The lesson website is viewed most easily by using [Jekyll](https://jekyllrb.com/). Once you install it for your system, you'll be able to build and view the site locally using `jekyll serve`. At that point, you'll notice that the bottom of lesson 7 (the contribution in this PR) renders differently from the other question-solution sections. I suspect that this is likely due to a minor syntax error. Feel free to let me know if I can clarify.

**Comment by amaji** [comment]
Thanks! I'll give it a try. Will ping you if I need more guidance.

**Comment by amaji** [comment]
@nhejazi Pushed a fix. It looked good on my side. Please review and let me know.

**Pull request merged**
