### PR TITLE
Stress the importance of `git status` (#685)

### LINKED ISSUE #685: Episode 3 suggests to use git status before initializing a repo, but does not show that
In a solution to a challenge in Episode 3 we say it would be good practice to check the status of the current directory just before issuing ``git init``. But this practice is not actually shown in the lesson.

As a side-effect, the lesson actually introduces ``git status`` without being explicit about it.
I find this a bit underhands.

### PR DESCRIPTION
**Pull request by jdvorak001**
Closes #685

Based on the discussion in the issue, I'm limiting the changes to just giving a bit of emphasis on the moment the `git status` command is first used.

### CODE REVIEW

**Review by kekoziar — COMMENTED** [review]
I'm not sure it's the same as `ls`. Maybe, instead of _It's the Git equivalent of listing a directory in a shell._ it can be _"It tells us the status of our project, and better, a list of changes in the project and options on how to resolve those changes"_

**Comment by jdvorak001** [comment]
Ok, I see it's a bit imprecise to say _the Git equivalent of ..._

**Review by kekoziar — APPROVED** [review]
I like it.  Thanks for the quick change.  I tagged another maintainer for review.

**Comment by martinosorb** [comment]
I like the idea of adding more emphasis on this command at that point. However, I think the phrasing is a bit off:

- _And now we will use what I think is the most important..._: I think nowhere in Carpentries materials the lessons use "I" -- who is "I" here?
- `git status` _reports on the status of our project. It tells us the status of our project..._ there is a clear repetition here

I would suggest something like _We can now start using one of the most important git commands, which is particularly helpful to beginners. `git status` tells us the status of our project, and better, a list of changes in the project and options on what to do with those changes. We can use it as often as we want, whenever we want to understand what is going on._

**Review by martinosorb — CHANGES_REQUESTED** [review]
See above.

**Comment by jdvorak001** [comment]
@martinosorb, your formulation is very good. I committed it with you as co-author.

**Review by martinosorb — APPROVED** [review]

**Comment by martinosorb** [comment]
Thank you so much!

**Pull request merged**
