### PR TITLE
Breaks up 01-backup.md in several topics

### LINKED ISSUE #29: Issues at 01-backup.md
From https://raw.githubusercontent.com/swcarpentry/lesson-template/gh-pages/tools/check.py:

- [x] Header section is missing expected row 'minutes'
- [x] Heading at line 28 should be level 2
- [x] Heading at line 75 should be level 2
- [x] Heading at line 128 should be level 2
- [x] Heading at line 273 should be level 2
- [x] Heading at line 510 should be level 2
- [x] Heading at line 595 should be level 2
- [x] Heading at line 692 should be level 2
- [ ] Document contains heading not specified in the template: Setting Up
- [ ] Document contains heading not specified in the template: Creating a Repository
- [ ] Document contains heading not specified in the template: Tracking Changes to Files
- [ ] Document contains heading not specified in the template: Changing a File
- [ ] Document contains heading not specified in the template: Exploring History
- [ ] Document contains heading not specified in the template: Recovering Old Versions
- [ ] Document contains heading not specified in the template: Ignoring Things
- [ ] The topic page should not have sub-headings outside of special blocks. If a topic needs sub-headings, it should be broken into multiple topics.

### PR DESCRIPTION
**Pull request by iglpdc**
Breaks the first topic of the lesson, `01-backup.md`, in 5 different topics, roughly corresponding to the sections in the previous version of `01-backup.md`. We need this to comply with the lesson template and to avoid having really long, unstructured topics. The new files are:

- `01-setup.md`: on how to setup your laptop for `git`,
- `02-create.md`: on how to create a repo with `git init`,
- `03-changes.md`: on the cycle of making changes, adding, and committing,
- `04-history.md`: on exploring history and restoring older versions,
- `05-ignore.md`: on how to use `.gitignore`.

Challenges have been moved to the end of the corresponding topic. The contents of each topic are not changed from the previous version. The rest of the topics (`collab`, `conflict`, and `open`) are renumbered appropriately. Some changes in other files are included to adapt to the new filenames. New time estimates are provided.

Fixes #29 .

### CODE REVIEW

**Comment by gvwilson** [comment]
We should merge or close other PRs against this lesson before landing this one...

**Comment by daisieh** [comment]
Shall I merge this now?

**Comment by iglpdc** [comment]
Hey, @daisieh, there is something wrong with this merge. Some of the latest commits are missing. For example, the new paragraphs on the text editors, merged by #56, are missing in the HEAD from both the markdown and the html files. 

We need to check what's going on before changing more things. I may have some time later today.

**Comment by daisieh** [comment]
AUGH.

**Comment by daisieh** [comment]
I probably stupidly forgot to update upstream before merging...I will try to fix this.

**Comment by daisieh** [comment]
I think that the problem is that the changes happened in 01-backup.md, not in 01-setup.md, so I need to manually replace the changes back to the new file.

**Pull request merged**
