### PR TITLE
Getting files to pass more validation checks.

### PR DESCRIPTION
**Pull request by gvwilson**
1.  Breaking 08-open into sub-files on licensing and hosting.
2.  Modifying other files to pass conformance checks.

### CODE REVIEW

**Comment by iglpdc** [comment]
Wait before merging this. I have a note somewhere saying that the changes introduced by #60 where lost at some point. I'll review it tonite or tomorrow.

**Comment by iglpdc** [comment]
And thanks, @gvwilson ! :-)

**Comment by wking** [comment]
On Sun, Apr 05, 2015 at 08:22:11AM -0700, Greg Wilson wrote:
> 1.  Breaking 08-open into sub-files on licensing and hosting.

If you want to push the electronic lab notebook section into a
callout, I'd drop it from the learning objectives.  That doesn't leave
anything in the learning objectives though, so either we should be
dropping this section entirely or we should drop the callout change.

**Comment by wking** [comment]
Also, the “How Reproducible Is My Work?” should probably have a
fallback paper for undergrads and early grad students that don't have
a body of recent papers to pull from.  And in any event, I have a hard
time imagining novices having time to do something as basic as finding
and rebuilding a LaTeX paper in however much of the allocated five
minutes remains after the instructor quiets down ;).  I'd probably
just drop this challenge.

**Comment by gvwilson** [comment]
Agreed.

**Comment by gvwilson** [comment]
We should have some kind of "see how hard reproducibility is" exercise 
here - can you suggest an alternative?

**Comment by wking** [comment]
On Sun, Apr 05, 2015 at 05:26:59PM -0700, Greg Wilson wrote:
> We should have some kind of "see how hard reproducibility is"
> exercise here - can you suggest an alternative?

Maybe we should spin this particular idea off into a new issue.  No
need to hold up the rest of this PR while we work this out, or to push
through a WIP reproducibility exercise before having time to figure
out what we want.  Can you amend your commit to drop that challenge in
this PR?

**Comment by iglpdc** [comment]
As I was saying before, this commit 5b84392, which introduced a note on creating DOIs for code and was merged in #60, got lost (maybe between #65 and #67?). 

@gvwilson, can you apply the patch for 5b84392 on top of the your `09-licensing.md`? Thanks.

**Comment by gvwilson** [comment]
Done - I think this is ready to merge, and then we can worry about putting the open science stuff into a separate repo.

**Comment by iglpdc** [comment]
Thanks! I'm merging.

**Comment by wking** [comment]
On Mon, Apr 06, 2015 at 08:34:49PM -0700, Ivan Gonzalez wrote:
> As I was saying before, this commit 5b84392, which introduced a note
> on creating DOIs for code and was merged in #60, got lost (maybe
> between #65 and #67?).

Looks like it was dropped by 18ca227 (Merging conflict, 2015-03-11,
#50):

  $ git show 18ca227 | grep -3 Digital
  - > ## Making Code Citable {.callout}
  - >
  - > [This short guide](https://guides.github.com/activities/citable-code/) from GitHub
  - > explains how to create a Digital Object Identifier (DOI) for your code.
  - 
  - ## Hosting
  -

**Pull request merged**
