### PR TITLE
Point out the importance of tracking text files (part of ResBaz train-the-trainer SWC training)

### PR DESCRIPTION
**Pull request by mscook**
Also, while I do believe the PhD comic does get the point across to novices (and something they can all relate to), I do **not** believe that planting the seed that you could track changes to Word documents is an entirely good idea.

### CODE REVIEW

**Comment by jiffyclub** [comment]
This has recently been covered via #36.

**Comment by andreabedini** [comment]
to be more specific (and provided I understand the discussion in #36), the text @mscook is proposing to include is already present in [discussion.md](https://github.com/swcarpentry/git-novice/blob/gh-pages/discussion.md#non-text-files)

**Comment by jiffyclub** [comment]
Exactly, thanks for clarifying.

**Comment by iglpdc** [comment]
@mscook I'm closing this without merging, as most of it is included in #36.

**Pull request closed without merging**
