### PR TITLE
Added a note on git bundles to section 12

### PR DESCRIPTION
**Pull request by razoumov**
This is for software carpentry certification (need to submit a small addition to the lessons). Thanks.

### CODE REVIEW

**Comment by daisieh** [comment]
Thanks for the contribution, @razoum486, and welcome to the team!

I was going to say that I wasn't sure if this was appropriate for the git-novice audience, but I don't think that I've ever even tried to teach lesson 12-hosting anyway, so certainly this is a good addition to the material in there *if* one wanted to teach it to a certain sort of audience. 

I've actually never heard of git bundles before: can you explain a little more about how one might make a bundle and then unpack it?

**Comment by razoum486** [comment]
Hi Daisie,
Sure, I can illustrate with an example. Let's say, there are two users, Nick and John, who have access to the same shared filesystem. Let's say, Nick creates a project, makes it a repository:
cd ~/projectgit initwork on the projectgit add <newFiles>git commit -a -m "describe changes"git bundle create ~/sharedFile HEAD   # bundle repository into a single filechmod og-wxr ~/sharedFile             # protect it from everyonesetfacl -m u:john:r ~/sharedFile      # but give read permission to John
In this example the file ~/sharedFile will be visible to John only. The last two lines just set the permissions; they are not necessary if Nick decides to email "sharedFile" as an attachment to John or share it via DropBox.
Next, John creates his own project, makes it a repository, pulls changes from Nick, works on the project, and then creates a bundle for Nick:
cd ~/projectgit initgit pull ~nick/sharedFile<work on the project>git add <newFiles>git commit -a -m "describe changes"git bundle create ~/sharedFile HEADchmod og-wxr ~/sharedFilesetfacl -m u:nick:r ~/sharedFile
Again, the last two lines are not necessary if "sharedFile" is exchanged via email or via a Dropbox link. From now on, the workflow for each user will be:
git pull ~collaboratorName/sharedFile<work on the project>git add <newFiles>git commit -a -m "describe changes"git bundle create ~/sharedFile HEADchmod og-wxr ~/sharedFilesetfacl -m u:collaboratorName:r ~/sharedFile
Every time a bundle is created, it should be given a unique name, or it could simply replace the old bundle file. Each repository (Nick's copy and John's copy) will contain the full project history as of the moment of their last pull. There is no central repository, and all collaboration is conducted in private.
Let me know if you have any questions.
Regards,
Alex RazoumovVisualization CoordinatorWestGrid / Compute Canada 


     On Wednesday, September 2, 2015 11:08 PM, Daisie Huang <notifications@github.com> wrote:
   

 Thanks for the contribution, @razoum486, and welcome to the team!I was going to say that I wasn't sure if this was appropriate for the git-novice audience, but I don't think that I've ever even tried to teach lesson 12-hosting anyway, so certainly this is a good addition to the material in there if one wanted to teach it to a certain sort of audience. I've actually never heard of git bundles before: can you explain a little more about how one might make a bundle and then unpack it?—

**Comment by gvwilson** [comment]
This is pretty cool, but it's much more advanced than any Gitting I've 
ever done...

**Comment by jiffyclub** [comment]
I agree that this is too advanced for our novice lesson.

**Comment by razoum486** [comment]
There is nothing particularly advanced in git bundles: instead of a repository you pull from a file that you send back and forth to your collaborator(s). If anything, this is much simpler than GitHub: no need to get an account, use web interface, etc. I used git bundles for years with collaborators and taught it for several years as one of the ways to exchange git revisions in my HPC class.
I assume I passed step 1 of SC instructor certification, right?
Alex Razoumov
 


     On Friday, September 4, 2015 11:01 AM, Matt Davis <notifications@github.com> wrote:
   

 I agree that this is too advanced for our novice lesson.—

**Comment by gvwilson** [comment]
Yup, this satisfies the instructor requirements - thanks.

**Comment by jiffyclub** [comment]
If there isn't already an existing guide on the web about how to collaborate using Git when hosting isn't an option I think it'd be great if you wrote one.

**Comment by iglpdc** [comment]
I'm closing this without merging as it's too advanced for the novice lesson. Thanks again @razoumov.

**Pull request closed without merging**
