### PR TITLE
Rename episodes/14-supplemental-rstudio.md to pre-i2a.md

### PR DESCRIPTION
**Pull request by hocuf**
Please delete this line and the text below before submitting your contribution.

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The Carpentries Team at team@carpentries.org.

---

### CODE REVIEW

**Comment by kekoziar** [comment]
@hocuf Will you please clarify the intention of this PR? Is there an issue or conversation regarding renaming the file?

**Review by kekoziar — COMMENTED** [review]
explicitly not approved.  Please clarify the PR request.

**Comment by hocuf** [comment]
Hello,

Of course, I would like to clarify this issue. The main purpose of creating this pull request was to change the file name so that I could more quickly understand what the file is and access its contents faster. I don't intend to be misleading or misleading in any way.

I would also like to mention the source of the repo I forked and renamed. My thought was that these changes would improve the overall readability and accessibility of the project. However, I recognise that no issue or conversation has been started on this, and perhaps it would have been more appropriate for me to start a discussion instead. I acknowledge that I made a mistake in this regard and will handle such situations more openly and transparently in the future.

I see that this has led to any confusion or misunderstanding and I apologise. I acted in good faith and certainly did not intend to steal or devalue the work of others. Going forward, I will take care to provide more communication and clarification before suggesting such changes. If you are genuinely uncomfortable with this situation, I can delete it immediately.

Best Regards
Abdullah
________________________________
Gönderen: K.E. Koziar ***@***.***>
Gönderildi: 20 Haziran 2023 Salı 19:33
Kime: swcarpentry/git-novice ***@***.***>
Bilgi: Abdullah Fatih Höcü ***@***.***>; Mention ***@***.***>
Konu: Re: [swcarpentry/git-novice] Rename episodes/14-supplemental-rstudio.md to pre-i2a.md (PR #931)


@hocuf<https://github.com/hocuf> Will you please clarify the intention of this PR? Is there an issue or conversation regarding renaming the file?

**Comment by hocuf** [comment]
Sorry. I did not get it. What is mean Closed #931?
________________________________
Gönderen: K.E. Koziar ***@***.***>
Gönderildi: 20 Haziran 2023 Salı 21:27
Kime: swcarpentry/git-novice ***@***.***>
Bilgi: Abdullah Fatih Höcü ***@***.***>; Mention ***@***.***>
Konu: Re: [swcarpentry/git-novice] Rename episodes/14-supplemental-rstudio.md to pre-i2a.md (PR #931)


Closed #931<https://github.com/swcarpentry/git-novice/pull/931>.

**Pull request closed without merging**
