### PR TITLE
Simplify the explanation on removing files in episode 3.

### PR DESCRIPTION
**Pull request by kiwifb**
More complicated considerations of matters covered in subsequent
episode should be deferred as discussed in issue #720.

Please delete this line and the text below before submitting your contribution.

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The Carpentries Team at team@carpentries.org.  

---

### CODE REVIEW

**Comment by kiwifb** [comment]
Apologies for my editor removing spaces at the end of lines automatically. This makes this PR look more complicated than it is.

**Review by kekoziar — APPROVED** [review]
Thank you, @kiwifb, for the improvements you've submitted for this exercise!  I made some minor grammar and style fixes.

**Comment by slel** [comment]
Nice. Minor quibble (maybe addressed elsewhere):
"the next lesson" should be "the next episode".

**Comment by kekoziar** [comment]
@slel  I thought I changed that, but I guess it got missed with the other cleanup.  Feel free to submit a PR making the correction!

**Comment by slel** [comment]
Done: see #826.

**Pull request merged**
