### PR TITLE
Revise assignment in part 7. In particular, eliminate the word "clone".

### PR DESCRIPTION
**Pull request by arokem**
As far as I could tell, this is the first time this command appears in this
lesson, and it seems that it should be explained before it assigned in an
exercise.

### CODE REVIEW

**Comment by arokem** [comment]
Besides, what is the answer to the question asked at the end of this exercise?

**Comment by iglpdc** [comment]
Hi, @arokem, thanks for the PR. I agree that `clone` shouldn't be introduced here. I guess this was at the end of the lesson before we split it.

The point of the exercise, as I see it, is to stress the idea that the repo in Github is a copy of your repo, history included, and not just a  copy of your files. So, the time stamps in Github reflect the time when you created the repo locally (even if this was months ago.) This may be counter intuitive for people: when you copy a file somewhere usually the timestamps reflect the time of the copy.

As for your changes, what do you (and the others) think about simplifying even more and say something like "go to the repo you just created in Github and check the timestamps"?

**Comment by arokem** [comment]
OK - I understand the question/answer now, but the point is lost here, because the repo and the files were both just created, so there is no distinction. How about changing things up a bit. For example, how about recycling question 2 from here? 

https://github.com/swcarpentry/recycling/blob/gh-pages/_posts/2014-10-01-assessment-collaborating-with-git.md

For the time being, I liked your suggestion for wording and implemented that.

**Comment by iglpdc** [comment]
Thanks @arokem! (and sorry for the delay in merging)

**Pull request merged**
