### PR TITLE
Link to Github line ending page

### PR DESCRIPTION
**Pull request by daisieh**
Add a link to Github’s suggested config for dealing with line endings. Addresses Issue #82

### CODE REVIEW

**Comment by iglpdc** [comment]
Good. Are you adding the html for any particular reason? Otherwise, we should drop it for the commit and then update it later.

**Comment by daisieh** [comment]
Just habit; I did `make preview` to verify the change and then committed the html as well as the md change. Is it hurting anything?

**Comment by wking** [comment]
On Tue, Apr 21, 2015 at 12:14:47PM -0700, Daisie Huang wrote:
> Just habit; I did `make preview` to verify the change and then
> committed the html as well as the md change. Is it hurting anything?

Not if it doesn't cause merge conflicts.  But since you just have one
commit, it's reasonably straightforward to drop the HTML changes.
Something like:

  $ git checkout line-endings  # get on your feature branch
  $ git checkout HEAD^ -- instructors.html  # clobber with the parent's HTML
  $ git commit -a --amend -v  # squash the old HTML into your commit
  $ git push --force $YOUR_PUBLIC_REMOTE line-endings

The last push is forced, so it's “update the remote's line-endings
branch to match my local copy.  I don't care if that loses remote
history”, which we need to replace your remote commit with the new
amended version.

**Comment by iglpdc** [comment]
Exactly ;-) If you could drop the html, we can merge it.

**Comment by daisieh** [comment]
Okay that is fancy Git voodoo. I will try.

**Comment by daisieh** [comment]
I strongly disapprove of this `HEAD^` rigmarole.

**Comment by iglpdc** [comment]
Great @daisieh! I'm merging.

**Pull request merged**
