### PR TITLE
Update 03-create.md

### PR DESCRIPTION
**Pull request by paulcraig**
I propose changing the home branch from master to main in keeping with current GitHub practice. I am submitting this as part of my teaching certification for Software Carpentries.

### CODE REVIEW

**Comment by sstevens2** [comment]
Hi @paulcraig!  Nice to "see" you here!  

Check out issue #761 for more discussion on this issue.  There needs to be material added to address this change earlier on so everyone can change their branch name early.  I suggested an option for that in issue #761 with how I do it in lessons.  Once that change gets added then all of your work changing "master" to "main" will be needed.  I'd recommend putting all your into one PR since they are related changes.  Could you maybe merge your other branches together into one branch/PR (maybe this one) and close the others (#794, #795, #796, #798, #799)?  Let me know if you have questions about how to do that.

**Comment by paulcraig** [comment]
Hi Sarah,

I’m on vacation this week and will address this by the following Tuesday

Paul

Sent from my iPhone

On Apr 19, 2021, at 4:59 PM, Sarah Stevens ***@***.******@***.***>> wrote:


Hi @paulcraig<https://github.com/paulcraig>! Nice to "see" you here!

Check out issue #761<https://github.com/swcarpentry/git-novice/issues/761> for more discussion on this issue. There needs to be material added to address this change earlier on so everyone can change their branch name early. I suggested an option for that in issue #761<https://github.com/swcarpentry/git-novice/issues/761> with how I do it in lessons. Once that change gets added then all of your work changing "master" to "main" will be needed. I'd recommend putting all your into one PR since they are related changes. Could you maybe merge your other branches together into one branch/PR (maybe this one) and close the others (#794<https://github.com/swcarpentry/git-novice/pull/794>, #795<https://github.com/swcarpentry/git-novice/pull/795>, #796<https://github.com/swcarpentry/git-novice/pull/796>, #798<https://github.com/swcarpentry/git-novice/pull/798>, #799<https://github.com/swcarpentry/git-novice/pull/799>)? Let me know if you have questions about how to do that.

**Comment by paulcraig** [comment]
Hi Sarah,

Will you have office hours next week when we can talk about this? I don’t know how to merge pull requests yet.

Paul

Paul A. Craig
Professor of Biochemistry
School of Chemistry & Materials Science
Rochester Institute of Technology
1 Lomb Memorial Drive
Building 08, Room A114
Rochester, NY 14623
Telephone: +1.585.475.6145


From: Sarah Stevens ***@***.***>
Reply-To: swcarpentry/git-novice ***@***.***>
Date: Monday, April 19, 2021 at 4:59 PM
To: swcarpentry/git-novice ***@***.***>
Cc: Paul A Craig ***@***.***>, Mention ***@***.***>
Subject: Re: [swcarpentry/git-novice] Update 03-create.md (#793)


Hi @paulcraig<https://github.com/paulcraig>! Nice to "see" you here!

Check out issue #761<https://github.com/swcarpentry/git-novice/issues/761> for more discussion on this issue. There needs to be material added to address this change earlier on so everyone can change their branch name early. I suggested an option for that in issue #761<https://github.com/swcarpentry/git-novice/issues/761> with how I do it in lessons. Once that change gets added then all of your work changing "master" to "main" will be needed. I'd recommend putting all your into one PR since they are related changes. Could you maybe merge your other branches together into one branch/PR (maybe this one) and close the others (#794<https://github.com/swcarpentry/git-novice/pull/794>, #795<https://github.com/swcarpentry/git-novice/pull/795>, #796<https://github.com/swcarpentry/git-novice/pull/796>, #798<https://github.com/swcarpentry/git-novice/pull/798>, #799<https://github.com/swcarpentry/git-novice/pull/799>)? Let me know if you have questions about how to do that.

**Comment by sstevens2** [comment]
Hi Paul!  Happy for you to come to office hours or coding meet up next week and we can merge them together.  Hint: it is merging the branches together.

**Comment by paulcraig** [comment]
I planning to join the coding meeting tomorrow at 2:30 PM your time, to learn to merge the multiple pull requests into one. I looked for some solutions, but I think I will break something if I try it on my own. This is still a black box to me. 

I did like the comment from srerickson (how do you link comments?)

Paul

> ## Default Branch Name
> 
> Source file changes are associated with a "branch." By default, Git will create a branch called `master` 
> when you create a new repository with `git init` (as explained in the next Episode). This term evokes 
> the racist practice of human slavery and the software development community has moved to adopt 
> more inclusive language. Notably, new repositories created through GitHub use `main` as the default
> branch name.
>
> With Git versions 2.28 and higher, you can set a different name for the initial branch. To set main as 
> the default branch name do:
>
> ~~~
> $ git config --global init.defaultBranch main
> ~~~
> {: .language-bash}

**Comment by kekoziar** [comment]
Multiple PRs were submitted covering the same change. Closing as this is a duplicate.

**Pull request closed without merging**
