### PR TITLE
New images

### PR DESCRIPTION
**Pull request by daisieh**
This should address issues #87 and #85, as well as unify the images under a single visual metaphor.

### CODE REVIEW

**Comment by r-gaia-cs** [comment]
@daisieh Thanks for this PR. The new images looks **awesome**. I send a pull request to your branch with a few improvements.

**Comment by iglpdc** [comment]
Yeah, @daisieh, it looks great! This is a big improvement. 

@r-gaia-cs can you see the text correctly or is still out of place in your browser?

**Comment by r-gaia-cs** [comment]
> can you see the text correctly or is still out of place in your browser?

Better now.

s

**Comment by iglpdc** [comment]
Great! This is big improvement, thanks again, @daisieh!

I see three things we may want to do before merging:

1) you should drop the changes in the html files, as @wking explained in #92.
2) in `git-committing.svg`, I'd put the arrows with `git add` horizontally. I find diagonal text harder to read in general. This is very personal opinion, so if you prefer it like this, I'm OK too.
3) in `github-collaboration.svg`, after Wolfman cloned the repo, I think his remote should be still Dracula's repo in Github (you have `origin` in the bottom panel pointing to Wolfman's planets as if he forked instead of just cloning.)

The rest looks fine to me. Thanks again for the great work!

**Comment by r-gaia-cs** [comment]
@iglpdc Was my fault the error of `origin` at Wolfman's local copy. Just send a pull request to @daisieh.

**Comment by daisieh** [comment]
Augh, I never know how to back out files from a commit. Is it harming anything to merge the html files? Won't they just get re-built next time anyway?

**Comment by daisieh** [comment]
I think I backed out the html file.

**Comment by iglpdc** [comment]
I think this is ready to merge. Thanks @daisieh and @r-gaia-cs!

**Pull request merged**
