### PR TITLE
suggestions of changes/unification in objectives

### PR DESCRIPTION
**Pull request by djarecka**

### CODE REVIEW

**Comment by djarecka** [comment]
I had some problems, but hopefully today I did what you were asking :)

I mage some changes to the objectives regarding your request - in some files I just come back to the previous version. 

I didn't change the new files (01-basics, 02-setup), but I noticed a new form with "understand" instead of "explain". I can change it if you want.

**Comment by iglpdc** [comment]
Thanks a lot @djarecka! I think it's good and I'm merging this.

**Comment by iglpdc** [comment]
Hey, @djarecka, your commits have your GitHub nickname as your full name. Do you want me to change it to "Dorota Jarecka"? (You don't have to do anything, just saying whether you want the change.) 

We are doing a release this week that will have a DOI and we want to have an [AUTHORS](https://github.com/swcarpentry/git-novice/blob/gh-pages/AUTHORS) file with everyone cited properly.

**Comment by djarecka** [comment]
Yes, please change to the full name - Dorota Jarecka (djarecka@gmail.com). Thanks!

**Pull request merged**
