### PR TITLE
Added a description of private hosting, resolves #237

### LINKED ISSUE #237: Expand discussion of hosting on github or bitbucket
I believe a major barrier for some students to using hosted VC services is that they do not want to make their code public. 

I'd like to see some small additions to the hosting section of the git lesson:

1. Github is free as long as your publicly host your code. 
2. Github will cost money for private hosting. 
3. Bitbucket offers unlimited free public and private repos to work on projects, papers, etc. that you may not want to be made public provided you register with a *.edu, .ac.il, edu.sg* email address.

### PR DESCRIPTION
**Pull request by avishek-r-kumar**
Added the following parts to the hosting section:

1. Github is free as long as your publicly host your code.
2. Github will cost money for private hosting, though academics can get five free private repos
3. Bitbucket offers unlimited free public and private repos to work on projects, papers, etc. that you may not want to be made public provided you register with a *.edu, .ac.il, edu.sg* email address.

This is a pull request I'm making for instructor-training

### CODE REVIEW

**Comment by gvwilson** [comment]
>  1. Bitbucket offers unlimited free public and private repos to work
>     on projects, papers, etc. that you may not want to be made public
>     provided you register with a /.edu, .ac.il, edu.sg/ email address.
>
What about .ac.uk and other academic addresses?

**Comment by avishek-r-kumar** [comment]
Bitbucket provides academic accounts for all high-level academic addresses according to their documentation.

**Comment by iglpdc** [comment]
Thanks @avishek-r-kumar. My understanding is that Bitbucket gives unlimited free repos for teams under 5  [1]. And it seems that gitlab.com has unlimited private repos for free [2]. However I think these are company policies that can vary with time and shouldn't be our job to keep up with them.

It's true that there's usually interest on that. So, what do you think about moving your discussion, updated to include what I mention above, into the instructor's guide? We could add a simple, more neutral comment in this file at the end of the previous paragraph saying "These different services provide a wide variety of options to host public and private repositories".

Instructors could mention the current state of things if someone asks for more details.

[1] https://bitbucket.org/
[2] https://gitlab.com/users/sign_in

**Comment by iglpdc** [comment]
I'm closing this as stale.

**Pull request closed without merging**
