### PR TITLE
Feature/improve objectives

### PR DESCRIPTION
**Pull request by vyasr**
This pull request replaces #296, which has gone quite stale. It incorporates the comments made in that PR, and it also makes a few additional changes (consistently using subdirectory instead of sub-directory, rewording some of the section on `git init`) to reduce cognitive load.

### CODE REVIEW

**Comment by vyasr** [comment]
@munkm sorry if you're not the right person to tag on this, but I'm not sure who typically reviews these. Should I be doing anything further on this PR? Thanks!

**Comment by kekoziar** [comment]
Hi, @vyasr. One of the reasons this has not been committed is there are many unrelated changes being submitted with one PR (this was also an issue with the referenced PR).  Lumping multiple unrelated changes into one PR delays committing changes that can be merged.  Generally speaking, an individual PR should be limited to one file and one related change. As an example, while I might have merged the correction to the hyphenated words, and possibly the edits to the challenges, I don't agree with the wording of the added learning objective. So, since they were submitted as one PR instead of three, everything is delayed.  

In terms of learning objectives, they should be measureable and stated in an active voice. You can't measure "to learn" or "understand," so the learning objectives should be "create a local Git repository", "locate the .git directory," and "describe the purpose of the .git directory"

**Comment by vyasr** [comment]
Got it. Would you like me to split this into separate PRs so that you can merge the easier pieces and we can discuss the others separately, or is it easier at this point to just leave it as one PR and wait for reviews?

**Comment by kekoziar** [comment]
I'd rather have four different PRs.

**Comment by vyasr** [comment]
OK, I can make a separate PR for each of these commits.

**Comment by munkm** [comment]
Awesome. Thank you so much @vyasr

**Comment by kekoziar** [comment]
Thanks, @vyasr!

**Comment by vyasr** [comment]
@munkm @kekoziar replaced with #704, #705, #706, and #707.

**Comment by kekoziar** [comment]
@vyasr, thanks for submitting the separate PRs!

**Pull request closed without merging**
