### PR TITLE
Updating from template

### PR DESCRIPTION
**Pull request by gvwilson**
This brings in new CSS from the `styles` repo via the `lesson-template` repo.

### CODE REVIEW

**Comment by r-gaia-cs** [comment]
@gvwilson Could you also build the HTML?

**Comment by r-gaia-cs** [comment]
@gvwilson You need to rebase this. I think will be easy to create a new merge from the scratch.

**Comment by gvwilson** [comment]
Easier to close this, pull from git-novice::gh-pages, then create a new PR?

**Comment by r-gaia-cs** [comment]
@gvwilson

~~~
$ cd git-novice
$ git checkout gh-pages
$ git pull upstream gh-pages
$ git branch -f updating-from-template
$ git checkout updating-from-template
$ git merge lesson-template/core
$ git push -f origin updating-from-template
~~~

This pull request will be update and be read to merge. =)

**Comment by iglpdc** [comment]
Thanks for the explanation, @r-gaia-cs.

**Comment by gvwilson** [comment]
Done - @iglpdc or @r-gaia-cs can you please merge?

**Comment by iglpdc** [comment]
Thanks!

**Comment by iglpdc** [comment]
Has the new style a gray background or we did something wrong? (Sorry, I cannot attach a screenshot).

**Comment by r-gaia-cs** [comment]
@iglpdc The HTML need to be update. I already did it and push it, check https://swcarpentry.github.io/git-novice/.

**Comment by iglpdc** [comment]
Great.

**Pull request merged**
