### PR TITLE
Addresses Issue 283 to double check the wd 

### PR DESCRIPTION
**Pull request by gallington**
Added a few lines to check the working directory is reset to the correct level after the last section.

### CODE REVIEW

**Comment by iglpdc** [comment]
Two things. One is that you added your commit on from an outdated repo. You can remove the old commit and rebase, but maybe it's easier to to the PR again in a fresh repo:

```
$ git checkout master
$ git pull upstream master
$ git checkout new-issue-283
(add your changes and submit the PR anew)
```
The second issue is that it'd be better not to assume that everyone has created the `moons` dir or that they created it under `planets`: some instructors may not to choose this exercise or use a different dir and some learners may accidentally create the repo in a different place. The safest is to ask everyone to go back to `planets` (see my comment in #283)

**Comment by gallington** [comment]
Great! Good call I thought of that later. Will go back and change it

**Comment by iglpdc** [comment]
Hey @gallington, do you have some time to work on this in the next couple of days? Otherwise I can add a commit on top of yours to finish it myself.

**Comment by gallington** [comment]
Sure! I was traveling but am back in office now. Pardon the delay.

**Comment by gvwilson** [comment]
Can this one be merged now?

**Comment by rgaiacs** [comment]
Hey @gallington, do you have some time to work on this in the next couple of days?

**Comment by ErinBecker** [comment]
This change already appears in the current version of the lesson. Closing this PR as it is no longer necessary. Thanks @gallington!

**Pull request closed without merging**
