### PR TITLE
Add clarification of working directory to start of Tracking Changes section

### PR DESCRIPTION
**Pull request by rgaiacs**
Cover #283 and #285.

### CODE REVIEW

**Comment by brainwane** [comment]
I'm wondering whether we should add sample expected output:

`~~~
/home/user/planets
~~~
{: .output}`

But since every learner will have a different path, that might cause more confusion than it addresses.

**Comment by rgaiacs** [comment]
> I'm wondering whether we should add sample expected output, e.g. /home/user/planets with the {: .output} formatting. But, since every learner will have a different path, that might cause more confusion than it addresses.

@brainwane I didn't understand how your comment is related with my pull request.

**Comment by brainwane** [comment]
Hi @rgaiacs -- sorry for not being clear. I was suggesting that, since your pull request includes a suggested addition where the instructor demonstrates an input (invoking `pwd` on the command line), it might be a good idea to also include an addition of sample output. But I'm also not absolutely certain of this and willing to be told "bad idea" or "let's put that in a separate issue". :)

**Comment by daisieh** [comment]
I think this looks good as-is. Usually the instructor is live-coding this as it happens, so the class would see the output.

**Comment by brainwane** [comment]
OK, thanks @daisieh! Suggestion withdrawn. :)

**Pull request merged**
