### PR TITLE
undo deletion of hosting section

### PR DESCRIPTION
**Pull request by daisieh**
Adding back the deleted hosting section from 04-open.md

(deleted in PR #50)

### CODE REVIEW

**Comment by iglpdc** [comment]
Maybe it's a good time 1)  to shorten the lesson a bit, as with the new license part will take more than before, 2) address the issues in #24 to comply with the lesson template.

**Comment by daisieh** [comment]
Can we go ahead and merge this now, and then we can merge the giant reconfiguring of lessons, then address #24, then work on shortening the lesson? I just want to linearize the current changes we're making and get them all merged first before diverging again.

**Comment by wking** [comment]
On Thu, Mar 12, 2015 at 02:08:31PM -0700, Daisie Huang wrote:
> Can we go ahead and merge this now, …

Removing and then re-adding content in a subsequent commit makes it
hard for Git to track the history of those lines.  In #67, I've
submitted this same change but with a tweaked history so Git can
follow the lines.

For the curious, the history tweak looked like:

  $ git checkout -b restore-hosting origin/pr/65
  $ echo 'a6f4be53eca3ba01bb739ea5bd73a11c563ac68a 133ee1a00468fd7583603e96cef90522c7bd0796 cfbbcb345e7af91524ba41cb03ef575f0e3a0140' -> .git/info/grafts
  $ git commit --amend
  $ git rm .git/info/grafts

to turn the tip commit from #65 (a6f4be53e) into a merge between its
old parent (133ee1a00) and the last master commit that had the Hosting
section (cfbbcb34).

**Comment by daisieh** [comment]
Well that just sounds like voodoo. Does that mean we can close this PR?

**Comment by jiffyclub** [comment]
:joy:

**Comment by daisieh** [comment]
I merged the other, so am closing this one.

**Comment by wking** [comment]
On Thu, Mar 12, 2015 at 04:01:59PM -0700, Daisie Huang wrote:
> Well that just sounds like voodoo.

info/grafts is described in gitrepository-layout(5), and there's an
example using it for something similar to this in
git-filter-branch(1).  But I agree that it's one of the more obscure
Git features ;).  Anyhow, I'm happy that we have the hosting section
back and ‘git blame’ works on it ;).

**Pull request closed without merging**
