### PR TITLE
Stress importance of reviewing diff before commit

### PR DESCRIPTION
**Pull request by nicholash**
Change made as part of Software Carpentry instructor training.

### CODE REVIEW

**Comment by jiffyclub** [comment]
:+1:

**Comment by wking** [comment]
Looks good to me :).

**Comment by andreabedini** [comment]
It might not be appropriate for inclusion in the notes but `git commit -v` is very useful too.

**Comment by wking** [comment]
On Thu, Feb 12, 2015 at 04:46:03PM -0800, Andrea Bedini wrote:
> It might not be appropriate for inclusion in the notes but `git
> commit -v` is very useful too.

That's what I always use ;), but I'm also not sure if it's going over
the student-uptake threshold or not.  For folks who are new to text
editors, it might be best to stick to the simpler default message
template.

**Comment by jduckles** [comment]
:+1:

**Comment by andreabedini** [comment]
> I'm also not sure if it's going over the student-uptake threshold or not.

agree it's unnecessary detail

:+1: for PR

**Comment by iglpdc** [comment]
Thanks @nicholash.

**Pull request merged**
