### PR TITLE
Add exercise on choosing appropriate commit message

### PR DESCRIPTION
**Pull request by mbonsma**
This is a multiple choice question designed to assess if the purpose of a commit message has been grasped. Answer (a) is not descriptive enough, answer (b) is too descriptive and redundant, and answer (c) is good - short but descriptive.

### CODE REVIEW

**Comment by iglpdc** [comment]
Thanks @mbonsma! One thing only: could you change the enumeration of the choices to be 1., 2. 3. instead of (a), (b), ... Just to match the style in the exercise just below.

**Comment by iglpdc** [comment]
@mbonsma in case you don't know, you can just make another commit to this very same branch, you don't have to make a new PR from scratch.

**Comment by mbonsma** [comment]
Thanks @iglpdc, I tried to fix it and the markdown went funny... I'll figure it out.

**Comment by iglpdc** [comment]
Great! Thanks a lot @mbonsma. I'm merging it.

**Pull request merged**
