### PR TITLE
Add challenge to 05-history.md

### PR DESCRIPTION
**Pull request by stevenhwu**
This is part of the requirements for SWC trainer session.
`git log <filename>` was not mentioned in `04-changes.md`.
Since both `git diff --staged` and `git diff commitID filename` are used previously.
This should be not be a big leap to introduce `git log --switch commitID filename`

### CODE REVIEW

**Comment by iglpdc** [comment]
Hi @stevenhwu. Thanks for your PR. I like `git log <filename>` to see which commits touched particular file. I don't think the summary statistics are important enough for a novice learner. 

What do you think about keeping the first part of your challenge, where you introduce `git log <filename>`, but instead of the `--stat` you use `--patch`? (The latter allows you to see the diff for each of the commits and is the way to clarify what's is really in there for those commits with not very explanatory commit messages.)

**Comment by stevenhwu** [comment]
I think this is a good idea. We probably can assume some novice users will not have very informative commit messages, and their repository is not huge. `--patch` should provide them with enough, but not overwhelming, information to explore their log.

**Comment by iglpdc** [comment]
@stevenhwu do you have some time this week to finish this?  If you don't, I could add the changes to your PR.

**Comment by stevenhwu** [comment]
Yes, I will work on this on Friday.

**Comment by iglpdc** [comment]
Great! Thanks!

**Comment by stevenhwu** [comment]
@iglpdc I update the challenge, can you please have a look and any comments/suggestions will be great. Cheers.

**Comment by iglpdc** [comment]
Thanks @stevenhwu !

**Pull request merged**
