### PR TITLE
started to fix bug reports from issue 29

### PR DESCRIPTION
**Pull request by psteinb**
NOTE: fixing the remaining issues would imply tearing apart 01-backup.md which is debatable

### CODE REVIEW

**Comment by abought** [comment]
+1 for these changes so far.

I'll let someone else decide how to deal with the subheadings issue.

**Comment by abought** [comment]
Silly question, but is there a designated maintainer / review process for this repo? 

I'd be happy to push the merge button here, but don't want to step on any toes. (or commit anything without performing x required check)

**Comment by psteinb** [comment]
+1

**Comment by gvwilson** [comment]
Jessica Hamrick (@jhamrick) and Ivan Gonzalez (@iglpdc) are the topic 
maintainers - folks, can you please have a look and push the button if 
you think things are ready?

**Pull request merged**
