### PR TITLE
Upgrade style 9.5.3

### PR DESCRIPTION
**Pull request by fmichonneau**
In preparation for the June 2019 release, we are going through the repositories to check for broken links and other issues. 

This PR upgrades this repo to using the most recent version of the lesson template. It also removes permalinks in the form of `/setup/` for instance. We found that using this approach makes the site unusable offline.

It uses `bundle` to manage jekyll and other dependencies. It's the approach that GitHub pages uses and ensures that you have the same environment as the one used by GitHub.

Let me know if you have any questions.

### CODE REVIEW

**Comment by kekoziar** [comment]
@fmichonneau  What version of Ruby & Jekyll is this built on?  I'm getting this error when attempting to run `jekyll serve` (or `make serve`):
```
$ jekyll serve
Traceback (most recent call last):
        5: from C:/Ruby25-x64/bin/jekyll:23:in `<main>'
        4: from C:/Ruby25-x64/bin/jekyll:23:in `load'
        3: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.8.5/exe/jekyll:11:in `<top (required)>'
        2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/plugin_manager.rb:48:in `require_from_bundler'
        1: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- bundler (LoadError)
```

**Comment by fmichonneau** [comment]
with this upgrade, we use `bundler` to mimic the environment GitHub uses to generate websites hosted by GitHub pages. To install it, you should be able to do a version of:

```
gem install bundler
```

(see [GitHub help page](https://help.github.com/en/articles/setting-up-your-github-pages-site-locally-with-jekyll) for various operating system instructions)

**Comment by munkm** [comment]
We proba

**Comment by munkm** [comment]
Sorry I accidentally hit close! @fmichonneau is the all in one the same as swcarpentry/git-novice#653 ? If so we probably want to merge that one first so that that new contributor is able to contribute to the lesson.

**Comment by fmichonneau** [comment]
not quite, the body of aio.md has changed. I think #653 can be closed in favor of this PR.

**Comment by munkm** [comment]
I'm hesitant about closing a PR from a new contributor. We want them to be welcomed to contribute.

**Comment by munkm** [comment]
@fmichonneau our current tip of gh-pages is ~130ish commits ahead of your branch. If i look back through the log it looks like you're about a year behind us. Can you update your branch to include updated changes? 

Also is there a discussion somewhere about updating from the makefile to bundler? I didn't see that come up in the styles repository, and it looks like `4b8263b` through `991e8ab` are unique to this PR and not part of the styles repo at all. Maybe they should be a separate PR from the styles PR since it's not a part of the styles repo?

**Comment by fmichonneau** [comment]
argh, sorry I mixed up my remotes. I'll update the PR to bring it up to date with HEAD.

**Comment by kekoziar** [comment]
I agree with @munkm about #653. It's bad form to ask a new contributor to make a change, then ignore/close the change they pushed.

**Comment by fmichonneau** [comment]
Re: Bundler, looking back at the notes, I now realize it's something that was discussed on a couple of occasions with the lesson infrastructure committee (e.g., [1](https://github.com/carpentries/lesson-infrastructure/issues/7), [2](https://github.com/carpentries/lesson-infrastructure/blob/fa79ab9bb16c1c20f27b74e69f7cb423d4f1d92e/2018-07-25-minutes.md)) but not with the maintainers. Sorry about that. Using bundler has several advantages compared to calling Jekyll directly. Bundler manages all the dependencies and creates the exact same environment that GitHub uses to generate the web pages. It's the approach that [GitHub recommends](https://help.github.com/en/articles/setting-up-your-github-pages-site-locally-with-jekyll#requirements). It also allows us to use [remote themes](https://github.blog/2017-11-29-use-any-theme-with-github-pages/) which will greatly simplify the work of maintainers in the future as lessons would always use the latest version of the template. About a quarter of The Carpentries lessons already use bundler. Using bundler is not necessary for this lesson release, and I can split this PR into several, so as maintainers, you can decide what to include. I was lumping these changes in a single PR as I'm going through the 30+ lesson repositories scheduled to be released to detect potential issues and I was trying to avoid having to create/track a ton of PR but I can split these changes into:

- upgrade to 9.5.3
- using bundler
- other fixes to the lesson

(or something else if you prefer), to make your job as maintainers easier.

**Comment by munkm** [comment]
Thanks for updating your branch and for linking to the discussion @fmichonneau! I was just confused as to when this was decided so it's helpful to see documentation of it some place. Thank you! 🙂 

I understand and appreciate that you're doing a big push to get all of the styles submitted to different lessons for the Carpentries. I (and I think we all) appreciate all of the work you're doing keeping things in sync and helping with lesson infrastructure. 

I personally like your proposal of splitting this PR into the three you've suggested! I think that will make it easier to thoroughly review these changes, since they're substantive. @kekoziar and I have been working hard to get the lesson ready for the release, so making some of this parallelizable between us will make sure we can review it in manageable timeframes/chunks. I know it's a bit more work on your end; I'm sorry about that!

**Comment by kekoziar** [comment]
Thanks for the info @fmichonneau. I was able to get it to render correctly on my work laptop.  I'm also very glad that the branch was brought up to current with the lesson. That added a bit to my confusion regarding this upgrade.

**Comment by kekoziar** [comment]
I also want to add my thanks, @fmichonneau, for your work updating the styles template.  I appreciate the care and work the community takes to ensure the lessons are stable - technically and pedagogically.  @munkm and I have been working through the checklist for lesson release, and I know this came as a bit of a surprise to me being pushed one week before that deadline. I would like to give the PR the due diligence it deserves.

**Comment by munkm** [comment]
I'm going to close this in favor of the three separate PRs that were brought up in the discussion here that will help us more thoroughly review the changes. I'll be happy to reopen if anything changes though!

**Comment by fmichonneau** [comment]
The 3 PRs that correspond to this one are:

- https://github.com/swcarpentry/git-novice/pull/662
- https://github.com/swcarpentry/git-novice/pull/663
- https://github.com/swcarpentry/git-novice/pull/665

**Pull request closed without merging**
