### PR TITLE
Refactor to forking

### PR DESCRIPTION
**Pull request by daisieh**
I forgot that I meant to suggest these changes to the main repository: this is basically what we taught at https://github.com/swcarpentry/git-novice/pull/168 and I thought that the revamped conflict and motivation + the new forking lesson went really well. I'd like to suggest incorporating them into the main repo.

Also, this would address https://github.com/swcarpentry/git-novice/pull/185 / https://github.com/swcarpentry/git-novice/issues/176

### CODE REVIEW

**Comment by daisieh** [comment]
@iglpdc, what do you think about merging these changes? I would love some more feedback before merging. I'd be happy to do the conflict resolution, though.

**Comment by daisieh** [comment]
I have run the lesson all the way through as presented here several times and have always made it to the end, with pretty good feedback. I think that introducing pull requests makes a nice capstone example as well, especially if you can introduce that capstone at the beginning as a thing you will learn to do in the lesson.

**Comment by daisieh** [comment]
I think that using the example of Andrew (or, you know, any other SWC instructor) is more relatable than Wolfman/Dracula, but I think that there are some residual bits left from their story in the text. I never can think of a good way to integrate them, so I just use random gibberish, or more recently, comments about Mars from _The Martian_.

**Comment by daisieh** [comment]
Do people generally get to 10-open, 11-licensing, and 12-hosting when they teach this lesson? I just realized that the reason I can always get to forking is because I never teach those. I also don't teach 06-ignore.

**Comment by daisieh** [comment]
I'd love to integrate this into the 5.4 lesson on bug barbeque day. What do you think, @iglpdc ?

**Comment by iglpdc** [comment]
@daisieh I'm closing this by now. Feel free to remake it after 5.4.

**Pull request closed without merging**
