### PR TITLE
Add challenge about fixing a remote with an invalid URL

### PR DESCRIPTION
**Pull request by lesteve**
This is part of the instructor training.

### CODE REVIEW

**Comment by iglpdc** [comment]
Thanks @lesteve : looks good! A couple of requests, since his is a slightly more advance challenge, although I think it's totally pertinent (it happens often during the workshops that someone mistypes the URL):

Could you add a line specifying how to enter the wrong URL. E.g.:

~~~
git remote add broken https://gitbuh.com/vlad/palnets.git 
~~~

or something like that. In this case, they still have the `origin` remote working and the instructor can give a solution that works for everybody.

Also, could you also please add the "solution" under the "Remotes in Github" section in [instructors.md](instructors.md)? A link to some docs for `git remote set-url` would be enough.

Thanks again!

**Comment by lesteve** [comment]
> Could you add a line specifying how to enter the wrong URL.

Sure I'll do that.

> Also, could you also please add the "solution" under the "Remotes in Github" section in instructors.md? A link to some docs for git remote set-url would be enough.

There is already a mention of git remote set-url in the [Collaborating](https://github.com/swcarpentry/git-novice/blob/gh-pages/instructors.md#collaborating) section. Do you want me to move it to the "Remotes in Github" section?

**Comment by iglpdc** [comment]
> There is already a mention of git remote set-url in the Collaborating section. Do you want me to move it to the "Remotes in Github" section?

Oh, I didn't notice that :) Nah, I think it's enough with the text already there.

**Comment by lesteve** [comment]
OK added the instruction to add a remote with an obviously invalid URL.

**Comment by iglpdc** [comment]
Great! Thanks a lot.

**Pull request merged**
