### PR TITLE
Addition of "Where Can I Share My Work?" exercise to Topic 10 - Open Science

### PR DESCRIPTION
**Pull request by mpfl**
This topic covers a lot of third-party repository/services such as Figshare, arXiV, GitHub and Zenodo, but there's no mention of services that researcher's home institution already offer, such as publication repositories or data repositories.

This new exercise aims to introduce students to these institutional services.

### CODE REVIEW

**Comment by wking** [comment]
On Tue, Mar 08, 2016 at 10:43:22PM -0800, Matthias Liffers wrote:
> This topic covers a lot of third-party repository/services such as
> Figshare, arXiV, GitHub and Zenodo, but there's no mention of
> services that researcher's home institution already offer, such as
> publication repositories or data repositories.

They are mentioned briefly here [1].  I'm not actually clear on the
distinction between the hosting topic (objective: “Explain different
options for hosting scientific work”) and the open topic (objective:
“Explain how a version control system can be leveraged as an
electronic lab notebook for computational work”).  It look slike the
lab-notebook angle is only covered in the last section of the open
topic, with the initial section being more of a pitch for a more
modern publishing process.  Maybe we can punt that initial section to
[2] and keep the focus on version control here?

[1]: https://github.com/swcarpentry/git-novice/blob/eea814bb88f9de830af3a6aa6bcebc0aa0e40316/13-hosting.md
[2]: https://github.com/swcarpentry/modern-scientific-authoring

**Comment by mpfl** [comment]
You're quite right. This exercise would be better placed in the Hosting topic. I was drawn to the "Open Science" title and neglected to pay close attention to the learning objective.

I would even humbly suggest that some of the topics within the lesson could even be spun out into a new lesson on open science. I understand how using Git and GitHub can help achieve the open science paradigm, but perhaps the material has grown beyond what a lesson on Git should cover.

**Comment by wking** [comment]
On Tue, Mar 08, 2016 at 11:46:15PM -0800, Matthias Liffers wrote:
> I would even humbly suggest that some of the topics within the
> lesson could even be spun out into a new lesson on open science. I
> understand how using Git and GitHub can help achieve the open
> science paradigm, but perhaps the material has grown beyond what a
> lesson on Git should cover.

I agree with that [1].

The lab-notebook section and bullet points in [2] (which are mostly
about constructing and archivable audit trail) also seem like they'd
be a good intro motivation for version control.  I think we already
cover that in [3] with “Understand the benefits of an automated
version control system”, so I'd be in favor of dropping the “open”
section entirely.

Other content like the sections on licensing [4] and citation files
[5] are also orthogonal to version control per se, but are closely
related if you're talking about what to put into a public, version
controlled repository.  I'd probably keep those in this lesson,
although I think it's a bit odd that we talk about CITATION files but
not about README files ;).

[1]: https://github.com/swcarpentry/git-novice/pull/253#issuecomment-194142794
[2]: https://github.com/swcarpentry/git-novice/blob/eea814bb88f9de830af3a6aa6bcebc0aa0e40316/10-open.md
[3]: https://github.com/swcarpentry/git-novice/blob/eea814bb88f9de830af3a6aa6bcebc0aa0e40316/01-basics.md
[4]: https://github.com/swcarpentry/git-novice/blob/eea814bb88f9de830af3a6aa6bcebc0aa0e40316/11-licensing.md
[5]: https://github.com/swcarpentry/git-novice/blob/eea814bb88f9de830af3a6aa6bcebc0aa0e40316/12-citation.md

**Comment by mpfl** [comment]
CITATION, LICENCE and README files are important pieces of metadata required to enable reuse, but they are version-control-repository-specific instances of metadata commonly used in other repositories that have different foci.

Credit, licensing and good documentation should be touched on in almost every topic "You know why documentation is important, so this is the accepted method of internal documentation in Python", and they are generic subjects that would work well in a generic meta-lesson on open science. But now I'm just repeating myself.

As it is, I'm new to the etiquette of contributing to open source projects. Should I close this pull request and resubmit a pull request for submitting my exercise to the Hosting topic?

**Comment by wking** [comment]
On Wed, Mar 09, 2016 at 01:40:39AM -0800, Matthias Liffers wrote:
> CITATION, LICENCE and README files are important pieces of metadata
> required to enable reuse, but they are
> version-control-repository-specific instances of metadata commonly
> used in other repositories that have different foci.

You could use them all in directories which you didn't version
control, so I don't think they are version-control specific.  But they
may be too small to be worth their own project-metadata lesson, and in
that case this lesson is probably the best place for them.

> Credit, licensing and good documentation should be touched on in
> almost every topic…

Fair enough, but both time and working memory are precious [1] ;).

> As it is, I'm new to the etiquette of contributing to open source
> projects. Should I close this pull request and resubmit a pull
> request for submitting my exercise to the Hosting topic?

That works, but you can also adjust your branch and (force) push an
updated version to your GitHub fork.  GitHub will update this PR
automatically to show the tip of your gh-pages branch (since that's
the branch of your repository which you used for your initial PR).

[1]: https://github.com/swcarpentry/instructor-training/issues/101#issuecomment-193944842

**Comment by mpfl** [comment]
I see! Isn't that clever? Makes perfect sense - it maintains the conversation history as changes are made to the branch so the entire pull request can be assessed more efficiently!

**Comment by iglpdc** [comment]
Thanks @mpfl ! I also agree that we should be spun in a new short lesson on open science: I'll open a new issue to refloat the idea.

I'm merging your exercise.

**Pull request merged**
