### PR TITLE
adds illustration of story

### PR DESCRIPTION
**Pull request by raynamharris**
Adds an illustration of the motivating story

### CODE REVIEW

**Comment by iglpdc** [comment]
Thanks, @raynamharris ! A minor thing: you have a typo in "planets". If it's easy to fix, could change it? Otherwise, I'll merge and we will address the typo some other time.

**Comment by raynamharris** [comment]
I can fix it on Monday. However, I’m thinking I’d rather have the illustration in the first episode when the story is utilized, rather than in the homepage. So maybe we close this PR and start a new one?

**Comment by iglpdc** [comment]
Yes, the first place where the story is used would be also good. You don't need to open a new PR (just change this one), but if you prefer to close it and open a new one it's also OK.

**Comment by raynamharris** [comment]
Okay @iglpdc I fixed the typo and move the figure to episode 3 where the dracula story ramps up. Let me  know what you think.

**Comment by iglpdc** [comment]
Thansk, @raynamharris ! Looks good to me.

**Pull request merged**
