### PR TITLE
fix links

### PR DESCRIPTION
**Pull request by fmichonneau**
use the `{% link ... %}` notation so the paths are correct for offline use

### CODE REVIEW

**Comment by kekoziar** [comment]
Hi, @fmichonneau.  Can you verify the change in episode 13 is supposed to be {{ swc_github }} and not {{ site.swc_github }}? My local rendering does not have a link for {{ swc_github }}

**Comment by kekoziar** [comment]
An additional note that I checked all other changes, and fixed a couple of small errors.  The {{ swc_github }} question in the above comment is the only item that needs verification prior to merging.

**Comment by munkm** [comment]
That item was also addressed in this PR: https://github.com/swcarpentry/git-novice/pull/649 and was a broken link in our lesson before that PR was merged.

**Comment by kekoziar** [comment]
@munkm, I'd guess that the reversion to the syntax previous to PR #649 is a mistake, and the correct syntax is  {{ site.swc_github }}.  Thank you for clarifying!

**Comment by kekoziar** [comment]
Verified link syntax fix.

**Comment by kekoziar** [comment]
@fmichonneau, I checked this locally, but not live. The links are broken live =(

**Comment by kekoziar** [comment]
@fmichonneau, nvm. The links are fixed. they were missing `{{ page.root }}` in front of the `{% link .. %}`

**Pull request merged**
