### PR TITLE
add link to conflict in glossary

### PR DESCRIPTION
**Pull request by maneesha**

### CODE REVIEW

**Review by kekoziar — CHANGES_REQUESTED** [review]
Thanks for adding the link, but it goes to a page that doesn't exist.

**Comment by maneesha** [comment]
Ugh, this is what I get for trying to put in changes during the workshop. Clearly I need to wait until I can focus.

**Comment by martinosorb** [comment]
Hi @maneesha , I'm a bit confused on what is going on here -- the link still seems not to work for me. I believe the previous version with `html` was correct, perhaps the mistake was in `..learners` instead of `../learners`? I think you know better than me how the Workbench links work. Could you check again please?

**Review by kekoziar — APPROVED** [review]
Thanks for updating the syntax. Link works on local render.

**Pull request merged**
