### PR TITLE
Draft of new setup

### PR DESCRIPTION
**Pull request by sstevens2**
mostly taken from the workshop template

Related to #735.  I understand if you want to wait until this gets sorted with the workshop template to merge.

### CODE REVIEW

**Comment by sstevens2** [comment]
cc: @munkm

**Comment by ErinBecker** [comment]
Woohoo! Thanks for putting this together @sstevens2! 

There are a couple of different solutions being explored in [this Google Doc](https://docs.google.com/document/d/1JhW0bmWs6vOzTZK6WfQvTB4FWPxqPqrewkxy9enVqMk/edit#). I think @brownsarahm mentioned the increased cognitive load on learners to having setup instructions scattered across each lesson page and recommended having a landing page for SWC workshops (similar to https://datacarpentry.org/genomics-workshop/setup.html). I'm not sure how this would work, given the plug-and-play nature of SWC workshops, but am exploring that idea on the linked GDoc. Please feel free to add your thoughts. The Curriculum Team (myself, @fmichonneau and @zkamvar) are meeting Tuesday to discuss and hopefully propose a longer-term solution.

**Comment by brownsarahm** [comment]
@munkm gets credit for recognizing that additional cognitive load, which prompted me to look at DC and see how it worked there, since linking out has been the setup there for months and it's at least been working enough no one made an issue to complain.

**Comment by kekoziar** [comment]
The issue is still being worked on.  
As an aside, the instructions in this PR are currently out of date.  The setup instructions on the [workshop template](https://carpentries.github.io/workshop-template/#git) are current.

**Comment by sstevens2** [comment]
@kekoziar - think we should close this PR then?

**Comment by kekoziar** [comment]
> @kekoziar - think we should close this PR then?

Hi, @sstevens2.  It's probably best to close this.  I'm hoping that someone takes the initiative to add headers to improve readability (https://github.com/swcarpentry/git-novice/issues/781), which would definitely make this PR stale.   

I really appreciate the work you put into this.  We can always revisit this solution should the setup and installation policy change/be resolved.

**Comment by sstevens2** [comment]
Sounds good!  Thanks @kekoziar!

**Pull request closed without merging**
