### PR TITLE
capitalize Git

### LINKED ISSUE #505: Make sure Git is properly capitalized
There may be a few instances of the word "Git" that are not properly capitalized. 

- We use "Git" when we are talking about the version control system, the protocol or to qualify some other word, as in "a Git repository".
- We use "`git`" (with back-ticks in markdown) when we are talking about the implementation of Git as program installed in a computer.
- We should not use "git" at all.

### PR DESCRIPTION
**Pull request by hdinkel**
I went through the git-novice material and made sure that all instances of "Git" are properly capitalized. Closes #505

### CODE REVIEW

**Comment by tkphd** [comment]
Looks better, thanks! The episodes all look correct, but several improper instances of "git" remain in [_extras/discuss.md](/swcarpentry/_extras/discuss.md) and [reference.md](/reference.md). Can you change those also?

**Comment by rgaiacs** [comment]
@hdinkel Thanks for the corrections.

@tkphd Can we merge this and have another pull request for `_extras/discuss.md` and `reference.md`?

**Comment by hdinkel** [comment]
I've created another pull request #569 instead of updating this one...
Hope this helps?

**Comment by munkm** [comment]
This is wonderful @hdinkel. Thank you so much for both of your contributions!

**Pull request merged**
